fix: draw 参数类型
antvis/G6 pull request #3290
Opened 2021-11-04 04:04 UTC by czq297297

group参数如果为空，draw返回值无法为IShape

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] commit message follows commit guidelines

##### Description of change

2021-11-04 04:05 UTC, czq297297 reviewed
review

2021-11-04 05:52 UTC, czq297297 reviewed
review

2021-11-04 09:25 UTC, Blakko commented on packages/core/src/interface/shape.ts
> +  draw: (cfg?: ModelConfig, group: IGroup) => IShape;
FYI
`TypeScript error TS1016: A required parameter cannot follow an optional parameter`

2021-11-16 07:12 UTC, Yanyan-Wang commented
感谢 pr

2021-11-16 07:12 UTC, Yanyan-Wang approved these changes

2021-11-16 07:15 UTC, Yanyan-Wang requested changes

2021-11-16 07:15 UTC, Yanyan-Wang commented on packages/core/src/interface/shape.ts
> +  draw: (cfg?: ModelConfig, group: IGroup) => IShape;
第一个参数是可选的，第二个参数不可以是必填的吧。可以把第一个参数也改为 cfg: ModelConfig

2021-11-19 10:57 UTC, Yanyan-Wang commented
抱歉不小心关了。已经重新打开。修复问题后将合并

2021-11-19 10:58 UTC, Yanyan-Wang commented
第一个参数是可选的，第二个参数不可以是必填的吧。可以把第一个参数也改为 cfg: ModelConfig

2023-03-20 03:54 UTC, closed without merging