fix: tests
antvis/G6 pull request #4449
Opened 2023-04-20 15:23 UTC by Yanyan-Wang

fix: tests

2023-04-20 15:33 UTC, Yanyan-Wang commented on packages/g6/src/runtime/controller/interaction.ts
> +    config: string | { type: string; key: string },
以 key 为主键区分同一个交互的多实例

2023-04-20 15:33 UTC, Yanyan-Wang commented on packages/g6/package.json
> +  "homepage": "https://g6.antv.antgroup.com/",
lint 自动调整了顺序🥲

2023-04-20 15:33 UTC, Yanyan-Wang commented on packages/g6/tests/unit/behaviors/brush-select-spec.ts
> +      expect(graph.transientCanvas.getRoot().childNodes.length).toBe(3);
transientCanvas 上增加了 node group 和 edge group

2023-04-20 15:33 UTC, Yanyan-Wang commented on packages/g6/tests/unit/plugins/minimap-spec.ts
> +        expect(pxCompare(viewport.style.left, 0)).toBe(true);
像素的对比，可能在不同环境中有细微差距，需要模糊比较

2023-04-21 01:33 UTC, hustcc requested changes

2023-04-21 01:33 UTC, hustcc commented on packages/g6/package.json
> +  "homepage": "https://g6.antv.antgroup.com/",
这些信息 bugs、repo 都放最下面吧，更有用的信息，比如 main、module、types、files 放前面。

2023-04-21 01:33 UTC, hustcc commented on packages/g6/package.json
> +  "homepage": "https://g6.antv.antgroup.com/",
lint 感觉使用的字母顺序，不符合常规。

2023-04-21 02:07 UTC, xiaoiver approved these changes

2023-04-21 03:31 UTC, hustcc approved these changes

2023-04-21 05:48 UTC, merged