feat: add image node
antvis/G6 pull request #5417
Opened 2024-02-04 05:36 UTC by spengjie

完成 #5398
![Image Node](https://github.com/antvis/G6/assets/13675865/8096b81b-0464-4983-9715-56f59a57524e)

2024-02-04 08:04 UTC, hustcc commented
等这个 [PR](https://github.com/antvis/G6/pull/5415) 合并之后，rebase 一下在合并和，因为那个分支修改了一些默认样式，会有一些截图会更新。

2024-02-04 08:06 UTC, hustcc commented
整体代码看了下，带么写的挺整齐的 👍🏻👍🏻👍🏻

2024-02-04 08:51 UTC, hustcc commented
@spengjie 合并一下父分支吧，然后记得更新下单测的截图。

2024-02-04 09:42 UTC, hustcc requested changes

2024-02-04 09:42 UTC, hustcc commented on packages/g6/src/elements/nodes/image.ts
> +    return {
参考 circle 根据 halo 的 lineWidth 处理一下 halo 的 x y width height，避免 halo 和 keyShape 有重叠。

2024-02-04 09:42 UTC, hustcc commented on packages/g6/src/elements/nodes/image.ts
> +    return {
这里的逻辑和 https://github.com/antvis/G6/pull/5420 应该很像，可以参考。

2024-02-04 09:43 UTC, hustcc commented on packages/g6/src/elements/nodes/base-node.ts
> +  protected drawHaloShape(attributes: ParsedBaseNodeStyleProps<KT>, container: Group) {
👍🏻

2024-02-05 02:37 UTC, Aarebecca commented on packages/g6/src/elements/nodes/image.ts
> +export class Image extends BaseNode<GImageStyleProps, GImage> {
提供一个默认属性吧，长款使用 32 即可 ～

2024-02-06 03:50 UTC, Aarebecca commented
你好，这边需要 rebase 一下解决冲突

2024-02-08 03:50 UTC, yvonneyx commented on packages/g6/src/elements/nodes/image.ts
> +export class Image extends BaseNode<GImageStyleProps, GImage> {
#5427 新增在基础节点设置默认宽高 32，Image 可以酌情考虑是否设置

2024-02-21 04:48 UTC, spengjie commented on packages/g6/src/elements/nodes/image.ts
> +    return {
已修复

2024-02-21 04:48 UTC, spengjie commented on packages/g6/src/elements/nodes/image.ts
> +export class Image extends BaseNode<GImageStyleProps, GImage> {
已设置默认长宽为50

2024-02-21 04:49 UTC, spengjie commented
> 你好，这边需要 rebase 一下解决冲突

已进行rebase

2024-02-21 05:49 UTC, hustcc commented
开始写官网 demo 了，多以可以参考 https://github.com/antvis/G6/pull/5452 做一个 DEMO，基本直接 cp 过来即可。

2024-02-22 03:32 UTC, hustcc commented on packages/g6/src/elements/nodes/image.ts
> +    return { ...keyStyle, ...haloStyle, width, height, anchor: [0.5, 0.5] as [number, number] } as HaloStyleProps;
这里应该不需要，会自动沿用 keyStyle 中的 anchor。

2024-02-22 03:33 UTC, hustcc commented on packages/g6/__tests__/demo/static/node-image.ts
> +import { Line } from '../../../src/elements/edges';
这个单侧可以参考 node-ellipse 的写法，然后这个写法和官网 demo 保持一致。

2024-02-22 09:45 UTC, hustcc commented on packages/g6/__tests__/demo/static/node-image.ts
> +import { Graph } from '../../mock';
import { Graph } from '../../../src';

2024-02-22 09:45 UTC, hustcc commented on packages/g6/__tests__/demo/static/node-image.ts
> +// todo: when test env, use SVG always.
这个注释也可以删除。

2024-02-22 09:45 UTC, hustcc commented on packages/g6/src/elements/nodes/base-node.ts
> +    console.log(style);
删除。

2024-02-22 09:48 UTC, spengjie commented on packages/g6/src/elements/nodes/image.ts
> +    return { ...keyStyle, ...haloStyle, width, height, anchor: [0.5, 0.5] as [number, number] } as HaloStyleProps;
已修改

2024-02-22 09:48 UTC, spengjie commented on packages/g6/__tests__/demo/static/node-image.ts
> +import { Line } from '../../../src/elements/edges';
已修改
![image](https://github.com/antvis/G6/assets/13675865/8af652b1-c04f-4c34-90b3-e70a47dcaaf7)

2024-02-22 10:37 UTC, spengjie commented on packages/g6/src/elements/nodes/image.ts
> +  }
已添加

2024-02-22 10:48 UTC, hustcc approved these changes

2024-02-22 10:48 UTC, merged