feat(v5): add rect node
antvis/G6 pull request #5420
Opened 2024-02-04 09:25 UTC by ai-qing-hai

新增 node rect。 
![Uploading image.png…]()

2024-02-04 09:30 UTC, Aarebecca commented on packages/g6/__tests__/demo/static/node-rect.ts
> +  await canvas.init();
这个应该不需要了

2024-02-04 09:32 UTC, ai-qing-hai commented on packages/g6/__tests__/demo/static/node-rect.ts
> +  await canvas.init();
我看其他案例都有， 后面不用等统一删了吧

2024-02-04 09:32 UTC, hustcc commented
PR 描述中的截图没有上传成功。PR 描述要么参考 https://github.com/antvis/G6/pull/5419 详细一些，要么参考 https://github.com/antvis/G6/pull/5415 有一个 todo list 看出做了哪些事情。

2024-02-04 09:34 UTC, hustcc requested changes

2024-02-04 09:34 UTC, hustcc commented on packages/g6/src/elements/nodes/rect.ts
> +    return {
参考 circle 根据 halo 的 lineWidth 处理一下 halo 的 x y width height，避免 halo 和 keyShape 有重叠。

2024-02-04 09:35 UTC, hustcc commented on packages/g6/__tests__/demo/static/node-rect.ts
> +  await canvas.init();
要不你这个 PR 直接全部删除了，这样后面的 PR 也可以参考删除掉。

2024-02-04 09:36 UTC, hustcc commented
![image](https://github.com/antvis/G6/assets/7856674/50b71521-58ca-4d29-99e4-e3f8db7ad3a0)

@ai-qing-hai  单测的 lint 报错了，应该是你电脑上的 husky 没有安装成功，理论上每次 commit 会对文件进行格式化。

2024-02-04 09:51 UTC, ai-qing-hai commented on packages/g6/src/elements/nodes/rect.ts
> +    return {
已修改

2024-02-04 09:51 UTC, ai-qing-hai commented on packages/g6/__tests__/demo/static/node-rect.ts
> +  await canvas.init();
已删除

2024-02-04 11:54 UTC, Aarebecca approved these changes

2024-02-04 11:58 UTC, hustcc requested changes

2024-02-04 11:58 UTC, hustcc commented on packages/g6/src/elements/nodes/rect.ts
> +import type { DisplayObjectConfig, PathStyleProps as GPathStyleProps, Group } from '@antv/g';
这段 import 放到前面，import order 有一些顺序的？

2024-02-04 11:58 UTC, hustcc commented on packages/g6/src/elements/nodes/rect.ts
> +
import 不留空行。

2024-02-04 11:58 UTC, hustcc commented on packages/g6/__tests__/demo/static/node-star.ts
> -  await canvas.init();
应该 circle 中也有一个，也一起删除吧。

2024-02-05 01:38 UTC, ai-qing-hai commented on packages/g6/__tests__/demo/static/node-star.ts
> -  await canvas.init();
circle 没有的

2024-02-05 02:14 UTC, ai-qing-hai commented on packages/g6/src/elements/nodes/rect.ts
> +
已删除

2024-02-05 02:31 UTC, Aarebecca commented on packages/g6/src/elements/nodes/rect.ts
> +
这里建议使用 `Polygon` 来绘制矩形，参考下面的逻辑，覆写一下 getIntersectPoint 方法，方便连接点计算

https://github.com/antvis/G6/blob/fafec34990bed86456b491d8d7146ca498c78a61/packages/g6/src/elements/nodes/star.ts#L68-L72

2024-02-05 03:07 UTC, ai-qing-hai commented on packages/g6/src/elements/nodes/rect.ts
> +
已改为 Polygon

2024-02-05 03:18 UTC, Aarebecca approved these changes

2024-02-05 03:18 UTC, merged