refactor: replace the animation return value with an event throw
antvis/G6 pull request #5445
Opened 2024-02-19 16:14 UTC by Aarebecca

动画相关 API 返回值统一为 `Promise<void>`，动画对象采用事件监听方式获取。

如调用 `await graph.draw()` 时，如果启用动画，则结果为动画完成状态。

---

The return value of the animation related API is unified as `Promise<void>`, and the animation object is obtained by event listening.

For example, when `await graph.draw()` is called, if animation is enabled, the result is animation completed.

2024-02-20 01:29 UTC, hustcc commented on .vscode/settings.json
> +    "afteranimation",
其他的 create、destroy、change、update 等都是动词，animation 是名词。

2024-02-20 01:49 UTC, hustcc requested changes

2024-02-20 01:49 UTC, hustcc commented on packages/g6/__tests__/demo/animation/controller-element-position.ts
> +  await graph.draw();
1. animate 的时间还是不应该包含在 draw 中
2. 事件参数，应该在 e 中包含（不同的事件，携带的数据可能不一样）

```ts
graph.once('beforeanimation', (e) => {
  console.log(e.results);
});

await graph.draw();
```

2024-02-20 01:49 UTC, hustcc commented on packages/g6/__tests__/demo/animation/controller-element.ts
> +  return await result;
同上。

2024-02-20 01:49 UTC, hustcc commented on packages/g6/__tests__/demo/utils/async.ts
> +}
不额外包方法，给开发者的的 API 就是监听事件，从事件的 event 中去获取数据 + 上下文。

2024-02-20 01:49 UTC, hustcc commented on packages/g6/src/runtime/element.ts
> +    invokeOnFinished(result, () => {
这里的代码逻辑有点复杂了，判断分支也很多（光判断 result 是否存在就有 3 个 if 了）。是否可以优化成以下：

```ts
if (result) {
  this.context.graph.emit(GraphEvent.BEFORE_ANIMATION,{ result });
  await result.finished;
  this.context.graph.emit(GraphEvent.AFTER_ANIMATION,{ result });
}
```

主要两个点：

1. onfinish 回调是为了给 render 函数知道什么之后动画结束，如果 render 只管渲染，动画都用事件抛出，就不需要了
2. `invokeOnFinished` 额外增加了一个 onfinish 的回调，这个和 await result.finished 区别是什么？

2024-02-20 08:21 UTC, hustcc commented on packages/g6/__tests__/demo/animation/controller-element-position.ts
> +  await graph.draw();
忽略， draw 和 layout 都包含动画时间。

2024-02-20 08:22 UTC, hustcc commented on packages/g6/__tests__/demo/utils/async.ts
> +}
忽略，不能在 G6 中 export 这样的方法即可。

2024-02-21 08:40 UTC, hustcc commented on packages/g6/src/runtime/element.ts
> +    return executeAnimatableTasks(tasks, {
nit: 只是感觉比较晦涩，还是在以前 js 的回调的语法上，改成用代码顺序执行的方式会更好。后面看看怎么修改好吧！

2024-02-21 08:41 UTC, hustcc commented on packages/g6/src/runtime/element.ts
> +    this.emit(new ElementZIndexChangeEvent(GraphEvent.AFTER_ELEMENT_Z_INDEX_CHANGE, id, zIndex));
事件确实要收敛一下了！z-index 的修改都要事件，有点太细节了。

2024-02-21 08:43 UTC, hustcc commented on packages/g6/src/utils/data.ts
> +  return !data.nodes?.length && !data.edges?.length && !data.combos?.length;
使用 get 方法，降低代码复杂度，提高单侧覆盖。

2024-02-21 08:48 UTC, hustcc approved these changes

2024-02-21 09:19 UTC, Aarebecca commented on packages/g6/src/runtime/element.ts
> +    this.emit(new ElementZIndexChangeEvent(GraphEvent.AFTER_ELEMENT_Z_INDEX_CHANGE, id, zIndex));
主要是后面 Histroy 会需要收集事件

2024-02-21 09:19 UTC, merged