chore: compact box layout demo
antvis/G6 pull request #5523
Opened 2024-03-12 11:52 UTC by lxfu1

## 遗留问题
1. collapse-expand-tree 功能未实现
2. `autoFit: 'center'` 和 animation 不能共存，非迭代布局可以先移动 viewport 再动画
3. node 配置不支持 callback

2024-03-12 12:47 UTC, hustcc commented on packages/g6/__tests__/demo/case/basic-compact-box.ts
> +export const basicCompactBox: STDTestCase = async (context) => {
命名规范为 layout-xxx，方便检索。包括文件名。

2024-03-12 12:48 UTC, hustcc commented on packages/g6/__tests__/demo/case/compact-box-left-align.ts
> +export const compactBoxLeftAlign: STDTestCase = async (context) => {
同上。

2024-03-12 12:49 UTC, hustcc commented on packages/site/examples/net/compactBox/demo/topToBottomCompactBox.js
> +import { Graph, Utils } from '@antv/g6';
demo 文件名改成 .ts 的

2024-03-12 13:04 UTC, yvonneyx commented
问题 3 目前已支持，具体改造可以查看此 PR https://github.com/antvis/G6/pull/5524

2024-03-12 13:15 UTC, hustcc requested changes

2024-03-12 13:17 UTC, Aarebecca commented on packages/g6/__tests__/demo/case/layout-basic-compact-box.ts
> +    animation: false,
animation 可以不用指定，context 里有配置的

2024-03-12 13:18 UTC, Aarebecca commented on packages/g6/__tests__/unit/layouts/basic-compact-box.spec.ts
> +    await expect(graph).toMatchSnapshot(__filename, 'basic_compact_box');
文件命名用短横线吧 `basic-compact-box`

2024-03-13 01:27 UTC, hustcc commented on packages/g6/__tests__/unit/layouts/basic-compact-box.spec.ts
> +    await expect(graph).toMatchSnapshot(__filename, 'basic_compact_box');
compact-box-basic

2024-03-15 04:56 UTC, closed without merging