feat: add hexagon node
antvis/G6 pull request #5527
Opened 2024-03-13 04:28 UTC by foolvip

2024-03-13 04:58 UTC, hustcc requested changes

2024-03-13 04:58 UTC, hustcc commented on packages/g6/src/utils/element.ts
> +
只留一行空行。

2024-03-13 04:58 UTC, hustcc commented on packages/g6/src/utils/element.ts
> +export function getHexagonPoints(outerR: number): Point[] {
增加单测。

2024-03-13 04:58 UTC, hustcc commented
另外，把官网的 demo 也修改一下。然后 pr 描述写一下，再留个截图。

2024-03-18 12:03 UTC, hustcc commented on packages/g6/src/elements/nodes/hexagon.ts
> +
空行删除。

2024-03-18 12:03 UTC, hustcc commented on packages/g6/src/elements/nodes/hexagon.ts
> +  protected getPoints(attributes: ParsedHexagonStyleProps): Point[] {
增加一个空行。

2024-03-18 12:03 UTC, hustcc commented on packages/g6/src/elements/nodes/hexagon.ts
> +
删除空行。

2024-03-18 12:04 UTC, hustcc commented
增加对于 hexagon 的截图测试。

2024-03-19 07:36 UTC, hustcc commented
![image](https://github.com/antvis/G6/assets/7856674/6dfba190-da36-4214-be58-48ed26417ad1)

badge 的位置好像不太对。

2024-03-20 05:20 UTC, foolvip commented
> ![image](https://private-user-images.githubusercontent.com/7856674/313962989-6dfba190-da36-4214-be58-48ed26417ad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTIyMjIsIm5iZiI6MTcxMDkxMTkyMiwicGF0aCI6Ii83ODU2Njc0LzMxMzk2Mjk4OS02ZGZiYTE5MC1kYTM2LTQyMTQtYmU1OC00OGVkMjY0MTdhZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDUxODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg0YmNmMWMzZjljYjNkYTA1Zjg5OTg3MzEyNThiMWI5OWUyZDI4MzM5YjQ1NWMwNzQ4MzJmYTIyNDI2ODRhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ejxn-jsjrTfw8OyVUSMLp-wL0WU06wEmsLHYZFqzh7M)
> 
> badge 的位置好像不太对。

看了下，应该是前几天项目中修改了demo中badge的参数写法。现在已经修改了并追加到之前的commit上了

2024-03-22 09:21 UTC, hustcc commented
@foolvip 单元测试报错了，尽快修改一下呗。

2024-03-22 10:34 UTC, foolvip commented
> @foolvip 单元测试报错了，尽快修改一下呗。

好了，删除node-hexagon.svg重跑下就行了

2024-03-22 11:04 UTC, hustcc approved these changes

2024-03-22 11:42 UTC, Aarebecca commented
CI 问题需要看下哈，需要格式化一下

2024-03-25 03:09 UTC, merged